In [1]:
import tensorflow as tf
import numpy as np
print(tf.__version__)

2.19.0


### Tensor

In [9]:
# Simple Tensors
a = tf.constant([[1,2],[3,4]])
print(a)
a = tf.random.normal(shape=(10,3))
print(a)

tf.Tensor(
[[1 2]
 [3 4]], shape=(2, 2), dtype=int32)
tf.Tensor(
[[-0.4651596  -0.8539137  -0.25799525]
 [ 0.27528653  1.2314875   0.560645  ]
 [ 0.53391385  1.2758503  -1.6841404 ]
 [ 2.6365745   1.6241635   0.19978046]
 [-0.04775254 -0.0859173  -1.2985988 ]
 [ 1.06283     0.9465916  -0.8372951 ]
 [ 1.3345139  -0.28215015 -0.56369656]
 [ 0.4384501  -0.03311989 -0.13612434]
 [ 1.9585599  -0.4552838  -0.28859288]
 [ 1.0223869   0.50663084  2.0662005 ]], shape=(10, 3), dtype=float32)


In [10]:
# To extract numpy-array from tensor, use .numpy()
print(a-a[0])
print(tf.exp(a)[0].numpy())

tf.Tensor(
[[ 0.          0.          0.        ]
 [ 0.7404461   2.0854013   0.81864023]
 [ 0.99907345  2.129764   -1.4261452 ]
 [ 3.1017342   2.4780772   0.4577757 ]
 [ 0.41740707  0.76799643 -1.0406035 ]
 [ 1.5279896   1.8005054  -0.57929987]
 [ 1.7996736   0.5717636  -0.30570132]
 [ 0.9036097   0.8207938   0.12187091]
 [ 2.4237194   0.39862993 -0.03059763]
 [ 1.4875464   1.3605446   2.3241959 ]], shape=(10, 3), dtype=float32)
[0.62803483 0.42574543 0.7725989 ]


### Variables

In [11]:
# to get a sum of all rows of tensor a
s = tf.Variable(tf.zeros_like(a[0]))
print(s)
for i in a:
    s.assign_add(i)

print(s)

<tf.Variable 'Variable:0' shape=(3,) dtype=float32, numpy=array([0., 0., 0.], dtype=float32)>
<tf.Variable 'Variable:0' shape=(3,) dtype=float32, numpy=array([ 8.749603 ,  3.8743386, -2.2398174], dtype=float32)>


In [12]:
# Much better way to do it:
tf.reduce_sum(a,axis=0)

<tf.Tensor: shape=(3,), dtype=float32, numpy=array([ 8.749603 ,  3.8743386, -2.2398174], dtype=float32)>